# Generated by Django 4.2.5 on 2023-10-12 18:01

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='deadline',
            field=models.DateTimeField(null=True, blank=True),
        )
    ]
