# Generated by Django 4.2.5 on 2023-10-12 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0002_remove_otp_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='deadline',
        ),
    ]
